name: Build SMS Detector APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: |
        cd android
        chmod +x gradlew
    
    - name: Generate release keystore
      run: |
        cd android/app
        keytool -genkey -v -keystore release.keystore -alias androidreleasekey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
    
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleRelease
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SMS-Detector-v1.0.${{ github.run_number }}
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Display APK Info
      run: |
        echo "✅ APK Build Successful!"
        echo "📱 APK Name: SMS-Detector-v1.0.${{ github.run_number }}"
        echo "📦 Download from: Actions -> This workflow run -> Artifacts"
        echo ""
        echo "Installation Instructions:"
        echo "1. Download the APK from Artifacts section above"
        echo "2. Enable 'Install from unknown sources' on Android"
        echo "3. Install the APK"
        echo "4. Grant SMS permissions"
        echo ""
        echo "Server Config:"
        echo "- API: http://192.168.1.150:3003"
        echo "- WebSocket: ws://192.168.1.150:3002"